sudo: required 
language: cpp
services:
  - docker
env:
  global:
    secure: "XPAijoGyBRdc0KQ7zC2FJvARC0pvQtJNVfyMZwm/e2huNUuPJxuG4TrG9ojbeXRNa+UU8/0rrjTZn3IKuv8aLsUsMytHNX/OeDJgIKcdUaUsplAPBo50b0bODXopw2dFo9zaXmCdCbxzIBCaZLr8WtV0B31V3ueLEAT4sDhzMXT3Uti2cCLLNSi7Fjn481X1/wNMEgmKb7gT/fXy9y9jsueARwLJOCY75a9UbnHOPQDeu0gUqxlF0BnIEsqKy3T3wAqQl0ifAjmBtEHqdzyRsGpPK5ps7Etm8W8NHwWVIIsZqRKDCvZIb5xk+YxNCrWleAfI7xLsNmOuWmeKsNsvWwwr0bWbyZ2JULERLNXwqpnlH8kZqojF33pkpaFi1dZ49qlA36AGSRFraDAWl6hN82vznjDssakuJIegqEOJkPQ5xldvUhd0px+DnnXk+nCQdJeSeF8EWu+6qfC5/iXcUkxzBspk1LhU9XelB5+KTNyB6w6CCrQDETLqIWCpAI9bYeCH2GDl+mTcmKXbgcH+AQ8LJfuJyPCQPckYLjSCMmG0LFJwE6BYKxRvrSfGykm1LhAWzLm6FpVVAHtysHj9fStgRv7IkofgcajzE6MrIkgUVnW9fvlk8gger0ckGBt2AqkYz/JSkC4cXWgXxHPVUwnetKHLb7bSdTN15aWSie4=" #BINTRAY_KEY

before_install:
  - mkdir $(pwd)/build
  - docker pull spielhuus/toolchain:latest
script:
  - sudo docker run -itd -v $(pwd)/repo:/repo --name conan_build spielhuus/toolchain /bin/bash 
  - sudo docker exec conan_build /bin/bash -c "git clone https://github.com/spielhuus/conan-libev.git /repo"
  - sudo docker exec conan_build /bin/bash -c "conan user -p $BINTRAY_KEY -r conan-cpp squawkcpp"
  - sudo docker exec conan_build /bin/bash -c "cd /repo && conan export . conan-cpp/latest && conan install Libev/4.24@conan-cpp/latest --build=Libev && conan upload Libev/4.24@conan-cpp/latest --all -r=conan-cpp"
  - sudo docker rm -f conan_build

